### ISSUE TITLE
Add project to .travis to run tests.

### ISSUE THREAD

**Issue by BernardoSilva** [onesky/api-library-php5#17]
Enable travis for this project so contributors can writ unit tests and ensure they are passing.

Just need to enable the switch on travis.

![activate_travis](https://cloud.githubusercontent.com/assets/1537510/8001421/8b81b764-0b5d-11e5-87ad-bca73bc58a46.png)

**Comment by BernardoSilva** [comment]
@VLMH Can you activate travis for this project? 
Just need that switch activated to be able to start running builds on travis.

**Comment by VLMH** [comment]
Of course! I have done for another API wrapper.
Wanna do it for a long time. Just wanna add some test cases first

**Comment by VLMH** [comment]
Done and the build will proceed when
- .travis.yml present
- pull request

Updated README.md

**Comment by BernardoSilva** [comment]
Awesome :+1: 
Thanks @VLMH 

I think you can close this issue.
Its already working on this PR: https://github.com/onesky/api-library-php5/pull/19
